services:
  govsuite-dms-fe:
    build:
      context: ${COMPOSE_BUILD_CONTEXT:-.}
      dockerfile: ${COMPOSE_DOCKERFILE:-Dockerfile}
    image: ${COMPOSE_IMAGE:-govsuite-dms-fe:latest}
    container_name: ${COMPOSE_CONTAINER_NAME:-govsuite-dms-fe}
    ports:
      - '${COMPOSE_PORT:-8080}:80'
    env_file:
      - .env
    restart: ${COMPOSE_RESTART_POLICY:-unless-stopped}
