services:
  govsuite-dms-fe:
    build:
      context: .
      dockerfile: Dockerfile
    image: govsuite-dms-fe:latest
    container_name: govsuite-dms-fe
    ports:
      - '8080:80'
    env_file: .env
    restart: unless-stopped
